# Generated by Django 3.0.7 on 2020-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_business_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('business_type', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField()),
                ('updation_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'facility',
                'db_table': 'facility',
            },
        ),
    ]
