# Generated by Django 3.0.7 on 2020-06-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='contact_name',
        ),
    ]
