# Generated by Django 3.0.7 on 2020-06-10 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_remove_facility_contact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'facility'},
        ),
        migrations.AlterModelManagers(
            name='facility',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='facility',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='email',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='password',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='username',
        ),
        migrations.AddField(
            model_name='facility',
            name='contact_email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='contact_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 14, 47, 54, 691399, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='updation_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 14, 48, 1, 90150, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='facility',
            table='facility',
        ),
    ]
